project:
  type: website

website:
  title: "Santiago Torres"
  navbar:
    left:
        - posts/index.qmd
    right:
        - icon: github
          href: https://github.com/briskycola
format:
  html:
    theme:
      - slate
    css: styles.css



